nt: its remote counterpart. If you want to integrate the remote changes, hint: use 'git pull' before pushing again. hint: See the 'Note about fast-forwards' in 'git push --help' for details.
usuario@Lenovo-PC MINGW64
~/Documents/Projectes-it/sprint-1/bookmark-landing-page
(feature/tailwind-implementation)
$ git pull origin feature/tailwind-implementation --rebase
From https://github.com/triflip/bookmark-landing-page
 * branch            feature/tailwind-implementation -> FETCH_HEAD
 Auto-merging README.md
 CONFLICT (content): Merge conflict in README.md
 error: could not apply fa03082... Readme millorat
 hint: Resolve all conflicts manually, mark them as resolved with
 hint: "git add/rm <conflicted_files>", then run "git rebase
 --continue".
 hint: You can instead skip this commit: run "git rebase --skip".
 Readme millorat

 # Conflicts:
 #       README.md

 # Please enter the commit message for your changes. Lines starting
 # with '#' will be ignored, and an empty message aborts the commit.
 #
 .git/COMMIT_EDITMSG [unix] (13:32 09/10/2025)
 1,1 Comienzo
 "~/Documents/Projectes-it/sprint-1/bookmark-landing-page/.git/COMMIT_EDITMSG"
 [UNIX] 19L, 560Bhint: its remote counterpart. If you want to integrate
 the remote changes,
 hint: use 'git pull' before pushing again.
 hint: See the 'Note about fast-forwards' in 'git push --help' for
 details.

 usuario@Lenovo-PC MINGW64
 ~/Documents/Projectes-it/sprint-1/bookmark-landing-page
 (feature/tailwind-implementation)
 $ git pull origin feature/tailwind-implementation --rebase
 From https://github.com/triflip/bookmark-landing-page
  * branch            feature/tailwind-implementation -> FETCH_HEAD
  Auto-merging README.md
  CONFLICT (content): Merge conflict in README.md
  error: could not apply fa03082... Readme millorat
  hint: Resolve all conflicts manually, mark them as resolved with
  hint: "git add/rm <conflicted_files>", then run "git rebase
  --continue".
  hint: You can instead skip this commit: run "git rebase --skip".
  Readme millorat

  # Conflicts:
  #       README.md

  # Please enter the commit message for your changes. Lines starting
  # with '#' will be ignored, and an empty message aborts the commit.
  #
  .git/COMMIT_EDITMSG [unix] (13:32 09/10/2025)
  1,1 Comienzo
  "~/Documents/Projectes-it/sprint-1/bookmark-landing-page/.git/COMMIT_EDITMSG"
  [UNIX] 19L, 560B:wq
  :wq
  :wq
  :wq
  :wq
  :wq
  Readme millorat